package com.axxessio.axx2sls.content.service.pdo;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;


@DynamoDBTable(tableName = "area")
public class Area extends Generic implements Comparable<Area>{

    private String id;

    private String name;
    private String folder;
    private Integer number;
    private Integer size;
    private Date date;
    private Long version;
    
    public Area() {}

    public Area(String newName, String newFolder, int newNumber, int newSize, Date newDate) {
    	this.name = newName;
        this.folder = newFolder;
        this.number = newNumber;
        this.size = newSize;
        this.date = newDate;
        this.version = null;
    }
    
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName = "folder")
	public String getFolder() {
		return folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	@DynamoDBAttribute(attributeName = "number")
	public Integer getNumber() {
		return number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@DynamoDBAttribute(attributeName = "size")
	public Integer getSize() {
		return size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@DynamoDBAttribute(attributeName = "date")
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

    @DynamoDBVersionAttribute
    public Long getVersion() {
        return version;
    }
 
    public void setVersion(Long version) {
        this.version = version;
    }
    
    @Override
    public String toString() {
        return String.format(
                "Area[id=%s, name='%s', folder='%s', number='%d', size='%d', date='%s']", id, name, folder, number, size, date.toString());
    }

    @Override
	public int compareTo(Area a) {
    	
		return name.compareToIgnoreCase(a.name); 
	}
}